scripts: gen_kobject_list: Fix error log call
A trivial bug that caused the following error when this situation
actually happened:

  Too many thread objects (21)
  Traceback (most recent call last):
    File "/zephyr/scripts/gen_kobject_list.py", line 307, in <module>
      main()
    File "/zephyr/scripts/gen_kobject_list.py", line 281, in main
      -(-thread_counter // 8))
  TypeError: write() takes exactly one argument (2 given)

With this commit, the detected error is printed correctly, e.g:

  Too many thread objects (21)
  Increase CONFIG_MAX_THREAD_BYTES to 3

Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>