samples: net: Disable native_sim net USB driver in samples
The native_sim USB driver gives this error currently if one
enables CONFIG_POSIX_API.

drivers/usb/device/usb_dc_native_posix_adapt.c:22:10: \
 fatal error: sys/un.h: No such file or directory
   22 | #include <sys/un.h>
      |          ^~~~~~~~~~
compilation terminated.

Disable the netusb support from networking shells for native_sim
board for now so that CI can pass.

Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>