samples: tfm_integration: replace nrf5340dk with nrf9161dk
Building for nrf5340dk cause link time failure as:

undefined reference to `tfm_platform_gpio_pin_mcu_select'

It only happens with this platform, not with other ones in the allow
list, therefore we pick another Nordic one as integration platform and
disable nrf5340dk.

Signed-off-by: Valerio Setti <vsetti@baylibre.com>