net: buf: fix designated initializer order
Compile with arm-none-eabi-g++ (10.2.0) fails with:
error: designator order for field 'net_buf_pool::free' does not match declaration order in 'net_buf_pool'
because C++ doesn't support out-of-order designated initializers.

Signed-off-by: Rihards Skuja <rihardssk@mikrotik.com>