tests: i2c_emul: Remove unused variable
Building with clang warns:

tests/drivers/i2c/i2c_emul/src/test_forwarding_buf.cpp:20:32: error:
unused variable 'targets' [-Werror,-Wunused-const-variable]
constexpr const struct device *targets[FORWARD_COUNT] = {
                               ^

Signed-off-by: Tom Hughes <tomhughes@chromium.org>